<a href="https://colab.research.google.com/github/cristhianchica12/cristhianchica12/blob/main/tareaEjercicionumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version
import numpy as np


Python 3.10.12


Ejercicios en clase


In [2]:
!python --version

Python 3.10.12


Arreglo de 1 dimension

In [3]:
import numpy as ap
practica=np.array([3,33,333])
print(practica)
print(practica.shape)


[  3  33 333]
(3,)


Funcion

In [6]:
import numpy as np
practica=np.array([3,33,333])
print(practica)
print(practica.shape)
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])
#print(b)

print(b[:,[2,3]])

[  3  33 333]
(3,)
(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]


In [9]:
c=np.random.randint(low=4,high=12,size=(4,5))

otro

In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=12,size=(2,2))




c

In [18]:
print(c)

[[ 8 10]
 [ 7  9]]


d

In [19]:
print(d)

[[2 2]
 [2 5]]


vertical


In [15]:
aux=np.vstack((c,d))
print(aux)

[[4 4]
 [7 9]
 [5 8]
 [5 2]]


horizontal

In [16]:
aux=np.hstack((c,d))
print(aux)

[[4 4 5 8]
 [7 9 5 2]]


In [20]:
c=np.random.randint(low=4,high=12,size=(9))
print(c)
print(c.shape)

[ 8  5  8 10  9  4  6  9  8]
(9,)
