<a href="https://colab.research.google.com/github/cristhianchica12/cristhianchica12/blob/main/tareaEjercicionumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Import numpy as np and see the version(Importar la version de numpy)

In [2]:
!python --version
import numpy as np


Python 3.10.12


Ejercicios en clase


In [ ]:
!python --version

Python 3.10.12


2. eate a 1D array of numbers from 0 to 9 (Arreglo de 1 dimensión del 0 al 9)

In [5]:
import numpy as ap
practica=np.array([0,1,2,3,4,5,6,7,8,9])
print(practica)
print(practica.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


3. Cree una matriz numpy de 3 × 3 de todos los True(Cree una matriz numpy de 3 × 3 de todos los True)

In [3]:
arreglo_3x3 = np.full((3, 3), True, dtype=bool)
print(arreglo_3x3)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract all odd numbers from arr

In [6]:
impares = practica[practica % 2 != 0]
print(impares)

[1 3 5 7 9]


5. Replace all odd numbers in arr with -1

In [8]:
practica[practica % 2 != 0] = -1
print(practica)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. Convert a 1D array to a 2D array with 2 rows

In [9]:
practica2 = practica.reshape(2, -1)
print(practica2)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


7. Stack arrays a and b vertically

In [11]:
a = np.array([19, 20, 32])
b = np.array([8, 7, 6])
vertical = np.vstack((a, b))
print(vertical)

[[19 20 32]
 [ 8  7  6]]


8. Stack the arrays a and b horizontally.

In [12]:
a = np.array([5, 6, 7])
b = np.array([22, 21, 20])
horizontal = np.hstack((a, b))
print(horizontal)

[ 5  6  7 22 21 20]


  9. Get all items between 5 and 10 from a.

In [13]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
rango_5_10= a[(a >= 5) & (a <= 10)]
print(rango_5_10)

[5 6 7 8 9]


10. How to make a python function that handles scalars to work on numpy arrays

In [14]:
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])


# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
# your code here
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(len(a)):
  tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


 11. Swap columns 1 and 2 in the array arr.

In [16]:
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arreglo = np.arange(9).reshape(3, 3)
print("Original:")
print(arreglo)

# Intercambiar las columnas 1 y 2
arreglo[:, [1, 2]] = arreglo[:, [2, 1]]

print(arreglo)

Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5

In [17]:
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_a = np.random.uniform(5, 10, (5, 3))

print(random_a)

[[9.34495342 6.63460686 9.55178342]
 [6.15241087 5.84611639 8.9274072 ]
 [5.95522155 5.27764098 6.83297135]
 [9.56418688 6.07553076 7.53787523]
 [6.03912103 7.52885899 5.47825577]]


Funcion

In [ ]:
import numpy as np
practica=np.array([3,33,333])
print(practica)
print(practica.shape)
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])
#print(b)

print(b[:,[2,3]])

[  3  33 333]
(3,)
(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(4,5))

otro

In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=12,size=(2,2))




c

In [ ]:
print(c)

[[ 8 10]
 [ 7  9]]


d

In [ ]:
print(d)

[[2 2]
 [2 5]]


vertical


In [ ]:
aux=np.vstack((c,d))
print(aux)

[[4 4]
 [7 9]
 [5 8]
 [5 2]]


horizontal

In [ ]:
aux=np.hstack((c,d))
print(aux)

[[4 4 5 8]
 [7 9 5 2]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(9))
print(c)
print(c.shape)

[ 8  5  8 10  9  4  6  9  8]
(9,)


Numeros mayores a 8

In [ ]:
filtro=(c>8)
print(c[filtro])

[10  9  9]


numeros menores a10

In [ ]:
filtro=(c<10)
print(c[filtro])

[8 5 8 9 4 6 9 8]


valores que son par

In [ ]:
c[c%2==0]

array([ 8,  8, 10,  4,  6,  8])

valores que son impar

In [ ]:
c[c%2!=0]

array([5, 9, 9])

remmplazar numeros impares

In [ ]:
c[c%2!=0]=100
print(c)

[  8 100   8  10 100   4   6 100   8]


rango de valores

In [ ]:
c[(c>5) & (c<10)]

array([8, 8, 6, 8])

ejercicio 10 del deber

In [ ]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])


# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
# your code here
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(len(a)):
  tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


Funcion vectorial

In [ ]:
newFuntionArrays=np.vectorize(maxx)
newFuntionArrays(a,b)

array([6, 7, 9, 8, 9, 7, 5])