<a href="https://colab.research.google.com/github/cristhianchica12/cristhianchica12/blob/main/tareaEjercicionumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Import numpy as np and see the version(Importar la version de numpy)

In [1]:
!python --version
import numpy as np


Python 3.10.12


Ejercicios en clase


In [ ]:
!python --version

Python 3.10.12


2. eate a 1D array of numbers from 0 to 9 (Arreglo de 1 dimensión del 0 al 9)

In [4]:
import numpy as ap
practica=np.array([0,1,2,3,4,5,6,7,8,9])
print(practica)
print(practica.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


3. Cree una matriz numpy de 3 × 3 de todos los True(Cree una matriz numpy de 3 × 3 de todos los True)

In [9]:
import numpy as np

practica = np.ones((3, 3), dtype=bool)


Funcion

In [ ]:
import numpy as np
practica=np.array([3,33,333])
print(practica)
print(practica.shape)
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])
#print(b)

print(b[:,[2,3]])

[  3  33 333]
(3,)
(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(4,5))

otro

In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=12,size=(2,2))




c

In [ ]:
print(c)

[[ 8 10]
 [ 7  9]]


d

In [ ]:
print(d)

[[2 2]
 [2 5]]


vertical


In [ ]:
aux=np.vstack((c,d))
print(aux)

[[4 4]
 [7 9]
 [5 8]
 [5 2]]


horizontal

In [ ]:
aux=np.hstack((c,d))
print(aux)

[[4 4 5 8]
 [7 9 5 2]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(9))
print(c)
print(c.shape)

[ 8  5  8 10  9  4  6  9  8]
(9,)


Numeros mayores a 8

In [ ]:
filtro=(c>8)
print(c[filtro])

[10  9  9]


numeros menores a10

In [ ]:
filtro=(c<10)
print(c[filtro])

[8 5 8 9 4 6 9 8]


valores que son par

In [ ]:
c[c%2==0]

array([ 8,  8, 10,  4,  6,  8])

valores que son impar

In [ ]:
c[c%2!=0]

array([5, 9, 9])

remmplazar numeros impares

In [ ]:
c[c%2!=0]=100
print(c)

[  8 100   8  10 100   4   6 100   8]


rango de valores

In [ ]:
c[(c>5) & (c<10)]

array([8, 8, 6, 8])

ejercicio 10 del deber

In [ ]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])


# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
# your code here
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(len(a)):
  tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


Funcion vectorial

In [ ]:
newFuntionArrays=np.vectorize(maxx)
newFuntionArrays(a,b)

array([6, 7, 9, 8, 9, 7, 5])